/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LosterRouteImport } from './routes/loster'

const LosterRoute = LosterRouteImport.update({
  id: '/loster',
  path: '/loster',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/loster': typeof LosterRoute
}
export interface FileRoutesByTo {
  '/loster': typeof LosterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/loster': typeof LosterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/loster'
  fileRoutesByTo: FileRoutesByTo
  to: '/loster'
  id: '__root__' | '/loster'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LosterRoute: typeof LosterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/loster': {
      id: '/loster'
      path: '/loster'
      fullPath: '/loster'
      preLoaderRoute: typeof LosterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LosterRoute: LosterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
